#!/usr/bin/env python3
"""Regenerate sitemap.xml by walking the repo for HTML pages.

Deterministic: same repo state -> same output. Run by the deploy workflow
before every publish; do not hand-edit sitemap.xml.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "https://shipwright-studio.pages.dev"
SKIP_DIRS = {"docs", ".github", ".wrangler", ".git"}


def page_url(rel):
    if rel == "index.html":
        return "/"
    assert rel.endswith("/index.html"), rel
    return "/" + rel[: -len("index.html")]


def meta(url):
    if url == "/":
        return ("weekly", "1.0")
    if url == "/ideas/":
        return ("daily", "0.9")
    if url.startswith("/lab/"):
        return ("monthly", "0.7")
    return ("monthly", "0.8")


def main():
    urls = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        if "index.html" in filenames:
            rel = os.path.relpath(os.path.join(dirpath, "index.html"), ROOT)
            urls.append(page_url(rel.replace(os.sep, "/")))
    urls.sort(key=lambda u: (u != "/", u))
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for u in urls:
        cf, pr = meta(u)
        lines += ["  <url>",
                  f"    <loc>{BASE}{u}</loc>",
                  f"    <changefreq>{cf}</changefreq>",
                  f"    <priority>{pr}</priority>",
                  "  </url>"]
    lines += ["  <!-- auto-generated by scripts/generate-sitemap.py; do not hand-edit. -->",
              "</urlset>", ""]
    out = os.path.join(ROOT, "sitemap.xml")
    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"sitemap.xml: {len(urls)} urls")


if __name__ == "__main__":
    main()
